### ISSUE TITLE
Ürün ortamı içinde Geçersiz API cevabı

### ISSUE THREAD

**Issue by H7ioo** [bilaleren/e-fatura#1]
Kolay gelsin, test ortamında herşeyi düzeldikten sonra ürün ortamına geçtim ve Geçersiz API cevabı aldım. 
```js
async function createInvoice(orders: Orders, date: string) {

  EInvoice.setTestMode(false);

  EInvoice.setCredentials({
    username: "X",
    password: "X",
  }); // Geçersiz API cevabı. 

 // ...Fatura oluşturma 

  await EInvoice.logout();
}
(async () => {
  await createInvoice([1,2,3], "08-09-2023");
})()
```
response: {
    data: undefined,
    errorCode: 2,
    httpStatusCode: 500,
    httpStatusText: 'Unknown'
  }

**Comment by bilaleren** [comment]
NodeJS 18 sürümü ile alakalı bir hata oluşuyormuş.

`EPROTO B8150000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled`
